- service: name=firewalld state=stopped enabled=false

- iptables:
   chain: INPUT
   ctstate: ESTABLISHED,RELATED
   jump: ACCEPT

- iptables:
   chain: INPUT
   protocol: tcp
   match: tcp
   destination_port: 22
   jump: ACCEPT

- iptables:
   chain: INPUT
   source: 93.41.96.136
   jump: ACCEPT

- iptables:
   chain: INPUT
   source: 172.93.54.0/24
   jump: ACCEPT

- iptables:
   chain: INPUT
   source: 127.0.0.1/8
   jump: ACCEPT

- iptables:
   chain: INPUT
   destination: 127.0.0.1/8
   jump: ACCEPT

- iptables:
   chain: INPUT
   source: 0.0.0.0/0
   jump: DROP
