- get_url:
    url:     "{{ spark_url }}"
    dest:    "/root/spark-{{spark_version}}.tar.gz"
- unarchive:
    copy: no
    src: "/root/spark-{{spark_version}}.tar.gz"
    dest: "/opt"
    creates: "/opt/spark-{{spark_version}}"
- file:
    src: "/opt/spark-{{spark_version}}"
    dest: "/opt/spark"
    state: link
- template: src=spark-env.sh dest=/opt/spark/conf/spark-env.sh mode=644
- template: src=spark-master.service dest=/lib/systemd/system/spark.service mode=644
  notify:
    - reload_systemd
  when: spark_master
- template: src=spark-slave.service dest=/lib/systemd/system/spark.service mode=644
  notify:
    - reload_systemd
  when: not spark_master
- service: name=spark.service state=started enabled=yes
